version: '3.4'

services:
  appdb:
    container_name: appdb
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - appdb-data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    ports:
      - ${PGA_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD} 

  recipe.api:
    container_name: recipe.api
    depends_on:
      - appdb
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@appdb:${DB_PORT}/${DB_NAME}
    ports:
      - "5000:5000" 