version: '3.4'

services:
  appdb:
    image: postgres
 
  pgadmin:
    image: dpage/pgadmin4

  recipe.api:
    image: ${DOCKER_REGISTRY-}recipe-api
    build:
      context: .
      dockerfile: ./Dockerfile 

volumes:
  appdb-data: